version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_NAME=Polynotes-prod
    ports:
      - 8080:80
    environment:
      - REACT_APP_NAME=PolyNotes-prod
