version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Polynotes-prod
    ports:
      - 8080:80
    environment:
      - REACT_APP_NAME=PolyNotes-prod
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    depends_on:
      - frontend
