# development docker-compose.yml
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3100:3100
    volumes:
      - ./frontend/src:/app/src:ro
    environment:
      - REACT_APP_NAME=PolyNotes-dev
      - CHOKIDAR_USEPOLLING=true
