# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb-polynote
    restart: always
    environment:
      MONGO_INITDB_DATABASE: polynote
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src:ro
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - mongo
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb_data_container:
