apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: polynotes
      type: front-end
      env: prod
  template:
    metadata:
      labels:
        app: polynotes
        type: front-end
        env: prod
    spec:
      containers:
        - name: polynotes
          image: lamenace90/polynotes-frontend:e5cb1fa
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
