namespace: charley

# External access to the service in a cluster
ingress:
  enabled: true
  name: "polynotes"
  serviceNameFront: "polynotes-frontend-charley"
  serviceNameBack: "polynotes-backend-charley"
  tls: true
  className: "nginx"
  host: "polynotes.cluster-2022-5.dopolytech.fr"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production

# status:
#   loadBalancer:
#     ingress: {{ toYaml .Values.ingress | nindent 4 }}

mongodb:
  auth:
    usernames:
    - "admin"
    databases:
    - "polynotes"
    existingSecret: "polynotes-charley-pwd"
