#
ProjectName: polynotes-charley

#
applications:
- name: polynotes-charley
  namespace: charley
  repoURL: https://github.com/charley04310/Polynotes.git
  chart: .helm/polynotes
  server: https://kubernetes.default.svc
- name: polynotes-frontend-charley
  namespace: charley
  repoURL: https://github.com/charley04310/Polynotes.git
  chart: frontend/.helm/deployment-frontend
  server: https://kubernetes.default.svc
- name: polynotes-backend-charley
  namespace: charley
  repoURL: https://github.com/charley04310/Polynotes.git
  chart: backend/.helm/deployment-backend
  server: https://kubernetes.default.svc
