name: Publish Docker image

on:
  push:
    branches: ["master"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      ## FRONTEND
      - name: Build Polynote Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: lamenace90/polynotes-frontend:${{ steps.commit.outputs.short }}
          labels: test
      ## BACKEND
      - name: Build Polynote backend IMage
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: lamenace90/polynotes-backend:${{ steps.commit.outputs.short }}
